### ISSUE TITLE
Uncaught exception that led into a high swap memory usage and collapse

### ISSUE THREAD

**Issue by bmarcote** [bmarcote/vlbi_calculator#3]
Bug to be Caught and Destroyed.

Raised by a running worker...

```
May 11 08:37:58 planobs planobs_runner[3645825]: [2021-05-11 08:37:57 +0200] [3645825] [ERROR] Exception in worker process
May 11 08:37:58 planobs planobs_runner[3645825]: Traceback (most recent call last):
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/home/marcote/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, i>
May 11 08:37:58 planobs planobs_runner[3645825]:     worker.init_process()
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/home/marcote/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 1>
May 11 08:37:58 planobs planobs_runner[3645825]:     self.load_wsgi()
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/home/marcote/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 1>
May 11 08:37:58 planobs planobs_runner[3645825]:     self.wsgi = self.app.wsgi()
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/home/marcote/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, i>
May 11 08:37:58 planobs planobs_runner[3645825]:     self.callable = self.load()
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/home/marcote/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49>
May 11 08:37:58 planobs planobs_runner[3645825]:     return self.load_wsgiapp()
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/home/marcote/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39>
May 11 08:37:58 planobs planobs_runner[3645825]:     return util.import_app(self.app_uri)
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/home/marcote/venv/lib/python3.8/site-packages/gunicorn/util.py", line 358, in i>
May 11 08:37:58 planobs planobs_runner[3645825]:     mod = importlib.import_module(module)
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
May 11 08:37:58 planobs planobs_runner[3645825]:     return _bootstrap._gcd_import(name[level:], package, level)
May 11 08:37:58 planobs planobs_runner[3645825]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
May 11 08:37:58 planobs planobs_runner[3645825]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
May 11 08:37:58 planobs planobs_runner[3645825]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
May 11 08:37:58 planobs planobs_runner[3645825]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
May 11 08:37:58 planobs planobs_runner[3645825]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
May 11 08:37:58 planobs planobs_runner[3645825]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/var/www/vlbiplanobs/app.py", line 37, in <module>
May 11 08:37:58 planobs planobs_runner[3645825]:     from astropy.time import Time
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/home/marcote/venv/lib/python3.8/site-packages/astropy/time/__init__.py", line 2>
May 11 08:37:58 planobs planobs_runner[3645825]:     from .formats import *  # noqa
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/home/marcote/venv/lib/python3.8/site-packages/astropy/time/formats.py", line 16>
May 11 08:37:58 planobs planobs_runner[3645825]:     from astropy import _erfa as erfa
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/home/marcote/venv/lib/python3.8/site-packages/astropy/_erfa/__init__.py", line >
May 11 08:37:58 planobs planobs_runner[3645825]:     from .core import *
May 11 08:37:58 planobs planobs_runner[3645825]:   File "/home/marcote/venv/lib/python3.8/site-packages/astropy/_erfa/core.py", line 40, >
May 11 08:37:58 planobs planobs_runner[3645825]:     from . import ufunc
May 11 08:37:58 planobs planobs_runner[3645825]: TypeError: data type 'i4' not understood
```

Which was followed by several exception of the type:
```
May 11 10:09:50 planobs planobs_runner[3647135]: Exception ignored in: <module 'collections.abc' from '/usr/lib/python3.8/collections/abc>
May 11 10:09:50 planobs planobs_runner[3647135]: Traceback (most recent call last):
May 11 10:09:50 planobs planobs_runner[3647135]:   File "<string>", line 1, in <module>
May 11 10:09:50 planobs planobs_runner[3647135]:   File "/home/marcote/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 2>
May 11 10:09:50 planobs planobs_runner[3647135]:     sys.exit(1)
May 11 10:09:50 planobs planobs_runner[3647135]: SystemExit: 1
```

And ultimately one error with multiple initialization issues, that led to a high swap consumption that forced a full shutdown of the virtual machine.

**Comment by bmarcote** [comment]
I think this bug was raised by a previously raised (uncaught) exception in the GUI (only there) from a wrong time stamp.
It should not happen again with v3.3.1.
