### ISSUE TITLE
Out-of-bounds in dirty map

### ISSUE THREAD

**Issue by bmarcote** [bmarcote/vlbi_calculator#6]
Apparently something different went out of bounds...

```
Apr 20 18:43:55 planobs planobs_runner[3170760]: multiprocessing.pool.RemoteTraceback:
Apr 20 18:43:55 planobs planobs_runner[3170760]: """
Apr 20 18:43:55 planobs planobs_runner[3170760]: Traceback (most recent call last):
Apr 20 18:43:55 planobs planobs_runner[3170760]:   File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
Apr 20 18:43:55 planobs planobs_runner[3170760]:     result = (True, func(*args, **kwds))
Apr 20 18:43:55 planobs planobs_runner[3170760]:   File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
Apr 20 18:43:55 planobs planobs_runner[3170760]:     return list(map(*args))
Apr 20 18:43:55 planobs planobs_runner[3170760]:   File "/var/www/vlbiplanobs/app.py", line 103, in smap
Apr 20 18:43:55 planobs planobs_runner[3170760]:     return f()
Apr 20 18:43:55 planobs planobs_runner[3170760]:   File "/var/www/vlbiplanobs/app.py", line 1370, in get_fig_dirty_map
Apr 20 18:43:55 planobs planobs_runner[3170760]:     dirty_map_nat, laxis = obs.get_dirtymap(pixsize=1024, robust='natural')
Apr 20 18:43:55 planobs planobs_runner[3170760]:   File "/var/www/vlbiplanobs/vlbiplanobs/observation.py", line 870, in get_dirtymap
Apr 20 18:43:55 planobs planobs_runner[3170760]:     uvimg[int(pixsize//2 + round(uv[0]*uvscaling)), int(pixsize//2 +round(uv[1]*uvscalin>
Apr 20 18:43:55 planobs planobs_runner[3170760]: IndexError: index 1251 is out of bounds for axis 1 with size 1024
Apr 20 18:43:55 planobs planobs_runner[3170760]: """
Apr 20 18:43:55 planobs planobs_runner[3170760]: The above exception was the direct cause of the following exception:
```

**Comment by bmarcote** [comment]
When setting the scale for the dirty maps, it was doing a small zoom-in, considering the convolution of the region equivalent to only the 90% of the longest baseline in the array. In a very few cases this led to the out-of-bounds errors.

Fixed now, although now the dirty maps cover a slightly larger field of view.
